apiVersion: v1
kind: Secret
metadata:
  name: metrics-overlay
stringData:
  metrics-overlay.yaml: |
    #@ load("@ytt:overlay", "overlay")
    #@overlay/match by=overlay.subset({"metadata":{"name":"external-dns"}, "kind": "Deployment"})
    ---
    spec:
      template:
        #@overlay/match missing_ok=True
        metadata:
          #@overlay/match missing_ok=True
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/path: "/metrics"
            prometheus.io/port: "7979"
